config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  root 'tasks#index'

  put 'tasks/:id/delete_image' => 'tasks#delete_image', as: :delete_image

  get 'api_tasks' => 'tasks#api_tasks'

end

app/models/task.rb
class Task < ActiveRecord::Base

  default_scope -> { order('number ASC') }
  validates :variant, presence: true, numericality: {:greater_than => 0}
  validates :number, presence: true, numericality: {:greater_than => 0}
  validates :univer, presence: true
  validates :solved, exclusion: { in: [nil] }

  has_attached_file :photo,
                    :url  => "/assets/tasks/:id/:basename.:extension",
                    :path => ":rails_root/public/assets/tasks/:id/:basename.:extension"
  validates_attachment_size :photo, :less_than => 6.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  def self.univer_search(univer_search)
    if !univer_search.nil? && !univer_search.empty?
      where('univer = ?', "#{univer_search}")
    else
      where(nil)
    end
  end

  def self.variant_search(variant_search)
    # if variant_search
    if !variant_search.nil? && !variant_search.empty?

        where('variant LIKE ?', "%#{variant_search}%")
    else
      where(nil)
    end
  end

  def self.type_t_search(type_t_search)
    # if type_t_search
    if !type_t_search.nil? && !type_t_search.empty?
        where('type_t LIKE ?', "%#{type_t_search}%")
    else
      where(nil)
    end
  end

  def self.solved_search(solved_search)
    # if solved_search
    if !solved_search.nil? && !solved_search.empty?
      logger.info('solved_search'+solved_search)
      where('solved = ?', "#{solved_search}")
    else
      where(nil)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    # @tasks = Task.univer_search(params[:univer_search]).variant_search(params[:variant_search]).solved_search(params[:solved_search]).type_t_search(params[:type_t_search]).paginate(page: params[:page])
    @tasks = Task.univer_search(params[:univer_search]).variant_search(params[:variant_search]).solved_search(params[:solved_search]).type_t_search(params[:type_t_search])
    @tasks1 = @tasks.page(params[:page]).per(20)
    params[:page] = (params[:page] == nil ? 1 : params[:page])
    if @tasks1.total_pages < params[:page].to_i
      params[:page] = @tasks1.total_pages.to_s
    end
    @tasks = @tasks.page(params[:page]).per(20)
    @solved = {"+" => "1", "-" => "0"}
  end

  def api_tasks
    # @tasks = Task.univer_search(params[:univer_search]).variant_search(params[:variant_search]).solved_search(params[:solved_search]).type_t_search(params[:type_t_search])
    # @tasks1 = @tasks.page(params[:page]).per(20)
    # params[:page] = (params[:page] == nil ? 1 : params[:page])
    # if @tasks1.total_pages < params[:page].to_i
    #   params[:page] = @tasks1.total_pages.to_s
    # end
    # @tasks = @tasks.page(params[:page]).per(20)
    # @solved = {"+" => "1", "-" => "0"}
    # render :template => 'tasks/api_tasks', :layout => false
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:success] = "Задача создана"
      redirect_to :back
    else
      render 'new'
    end
  end


  def edit
    @task = Task.find(params[:id])
  end


  def update
    @task = Task.find_by_id(params[:id])
    if @task.update_attributes(task_params)
      flash[:success] = "Задача обновлена"
      redirect_to @task
    else
      render 'edit'
    end
  end

  def show
    @task = Task.find(params[:id])
  end


  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end

  def delete_image
    @task = Task.find(params[:id])
    @task.photo = nil
    @task.save!
    redirect_to :back
  end

  private

  def task_params
    params.require(:task).permit(:russian_text, :czech_text, :type_t, :solved,
                                 :variant, :number, :answer, :photo, :univer)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    options = {
        filter_html:     true,
        hard_wrap:       true,
        link_attributes: { rel: 'nofollow', target: "_blank" },
        space_after_headers: true,
        fenced_code_blocks: true

    }

    extensions = {
        autolink:           true,
        superscript:        true,
        disable_indented_code_blocks: true,
        tables: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag %>
  <title>Библиотека задач</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container theme-showcase" role="main">
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @task.errors.any? %>
    <div class="alert alert-danger">
      При заполнении формы возникли ошибки.
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/tasks/_index_filter.html.erb
<div class="form-group">
  <form id="index_filter_form">
    <div class="col-sm-4">
      <%= select_tag "univer_search", options_for_select({'Масариков университет' => '2', 'Технический университет Брно' => '1'}, params[:univer_search]), prompt: "Выбрать универ", class: 'form-control' %>
    </div>
    <div class="col-sm-4">
      <%= select_tag "variant_search", options_from_collection_for_select(Task.select(:variant).uniq, "variant", "variant", params[:variant_search]), prompt: "Выбрать вариант", class: 'form-control' %>
    </div>
    <div class="col-sm-4">
      <%= select_tag "type_t_search", options_from_collection_for_select(Task.select(:type_t).uniq, "type_t", "type_t", params[:type_t_search]), prompt: "Выбрать тип", class: 'form-control' %>
    </div>
    <div class="col-sm-4">
      <%= select_tag "solved_search", options_for_select(@solved, params[:solved_search]), prompt: "Выбрать решенные", class: 'form-control' %>
    </div>
    <a style="display: none;" class="current_page" href="/tasks?page=<%= @tasks.current_page %>" data-remote="true">current_page</a>
  </form>
</div>

app/views/tasks/_masarikov.html.erb
<div style="display: none" id="masarikov">

  <div>
    <a id="masarikov_hide" class='btn btn-primary'>Назад</a>
  </div>

  <hr/>

  <% if @tasks_masarikov.any? %>

      <div class="form-group">
        <div class="col-sm-4">
          <%= select_tag "variant_search", options_from_collection_for_select(@tasks_masarikov.select(:variant).uniq, "variant", "variant"), prompt: "Выбрать вариант", class: 'form-control' %>
        </div>
        <div class="col-sm-4">
          <%= select_tag "type_t_search", options_from_collection_for_select(@tasks_masarikov.select(:type_t).uniq, "type_t", "type_t"), prompt: "Выбрать тип", class: 'form-control' %>
        </div>
        <div class="col-sm-4">
          <%= select_tag "solved_search", "<option value='1'>+</option><option value='0'>-</option>".html_safe, prompt: "Выбрать решенные", class: 'form-control' %>
        </div>
      </div>

      <%= will_paginate @tasks_masarikov, renderer: BootstrapPagination::Rails %>
      <table class="table table-hover">
        <tr>
          <th>Вариант</th>
          <th>№</th>
          <th>Тип</th>
          <th>Решена</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

        <% @tasks_masarikov.each do |task| %>
            <tr>
              <td><%= task.variant %></td>
              <td><%= task.number %></td>
              <td><%= task.type_t %></td>
              <td><%= (task.solved ? '+' : '-') %></td>
              <td><%= link_to image_tag(Rails.public_path+'/menu55.png'), task %></td>
              <td><%= link_to image_tag(Rails.public_path+'/edit45.png'), edit_task_path(task) %></td>
              <td><%= link_to image_tag(Rails.public_path+'/delete96.png'), task, method: :delete,
                              data: {confirm: 'Вы уверены?'} %></td>
            </tr>
        <% end %>
      </table>

      <%= will_paginate @tasks_masarikov, renderer: BootstrapPagination::Rails %>

  <% else %>
      <h3 style="text-align: center">Задач пока нет</h3>
  <% end %>

  <br/>
</div>

app/views/tasks/_tasks_list.html.erb
<% if @tasks.any? %>
    <br/>
    <div id="paginator" style="float: none">
      <%= paginate @tasks, :remote => true %>
    </div>
    <br/>

    <table class="table table-hover">
      <thead>

      <tr>
        <th>Вариант</th>
        <th>№</th>
        <th>Тип</th>
        <th>Решена</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody id="tasks_content">
      <%= render 'tasks_list_tr' %>
      </tbody>
    </table>


<% else %>
    <h3 style="text-align: center">Задач пока нет</h3>
<% end %>

app/views/tasks/_tasks_list_tr.html.erb
<% @tasks.each do |task| %>
    <tr>
      <td><%= task.variant %></td>
      <td><%= task.number %></td>
      <td><%= task.type_t %></td>
      <td><%= (task.solved ? '+' : '-') %></td>
      <td><%= link_to image_tag(Rails.public_path+'/menu55.png'), task %></td>
      <td><%= link_to image_tag(Rails.public_path+'/edit45.png'), edit_task_path(task) %></td>
      <td><%= link_to image_tag(Rails.public_path+'/delete96.png'), task, method: :delete,
                      data: {confirm: 'Вы уверены?'} %></td>
    </tr>
<% end %>

app/views/tasks/_vutbr.html.erb
<div style="display: none" id="vutbr">

  <div>
    <a id="vutbr_hide" class='btn btn-primary'>Назад</a>
  </div>

  <hr/>
  <% if @tasks_vutbr.any? %>

      <%= will_paginate @tasks_vutbr, renderer: BootstrapPagination::Rails %>
      <table class="table table-hover">
        <tr>
          <th>Вариант</th>
          <th>№</th>
          <th>Тип</th>
          <th>Решена</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

        <% @tasks_vutbr.each do |task| %>
            <tr>
              <td><%= task.variant %></td>
              <td><%= task.number %></td>
              <td><%= task.type_t %></td>
              <td><%= (task.solved ? '+' : '-') %></td>
              <td><%= link_to image_tag(Rails.public_path+'/menu55.png'), task %></td>
              <td><%= link_to image_tag(Rails.public_path+'/edit45.png'), edit_task_path(task) %></td>
              <td><%= link_to image_tag(Rails.public_path+'/delete96.png'), task, method: :delete,
                              data: {confirm: 'Вы уверены?'} %></td>
            </tr>
        <% end %>
      </table>

      <%= will_paginate @tasks_vutbr, renderer: BootstrapPagination::Rails %>

  <% else %>
      <h3 style="text-align: center">Задач пока нет</h3>
  <% end %>
  <br/>
</div>

app/views/tasks/api_tasks.erb
<%= render 'tasks_list' %>

app/views/tasks/edit.html.erb
<h1>Редактирование задачи</h1>

<%= form_for(@task, :html => {:class => 'form-horizontal', :role => 'form', multipart: true}) do |f| %>

    <%= render 'shared/error_messages' %>

    <div class="form-group">
      <%= f.label :univer, "Университет", :class => 'control-label col-sm-5' %>
      <div class="col-sm-3">
        <%= f.select :univer, options_for_select([['Технический университет Брно', 1], ['Масариков университет', 2]], @task.univer), {}, {:class => "form-control"} %>
      </div>
      <div class="col-sm-4">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :variant, "Вариант №", :class => 'control-label col-sm-5' %>
      <div class="col-sm-3">
        <%= f.number_field :variant, :class => 'form-control' %>
      </div>
      <div class="col-sm-4">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :number, "Номер задачи", :class => 'control-label col-sm-5' %>
      <div class="col-sm-3">
        <%= f.number_field :number, :class => 'form-control' %>
      </div>
      <div class="col-sm-4">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :type_t, "Тип задачи", :class => 'control-label col-sm-5' %>
      <div class="col-sm-3">
        <%= f.text_field :type_t, :class => 'form-control' %>
      </div>
      <div class="col-sm-4">
      </div>
    </div>


    <div class="form-group">
      <%= f.label :czech_text, "Чешский текст", :class => 'control-label col-sm-5' %>
      <div class="col-sm-4">
        <%= f.text_area :czech_text, :class => 'form-control' %>
      </div>
      <div class="col-sm-4">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :russian_text, "Русский текст", :class => 'control-label col-sm-5' %>
      <div class="col-sm-4">
        <%= f.text_area :russian_text, :class => 'form-control' %>
      </div>
      <div class="col-sm-3">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :photo, "Добавить изображение", :class => 'control-label col-sm-5' %>
      <div class="col-sm-3">
        <%= f.file_field :photo, :class => 'filestyle', :accept => 'image/png,image/gif,image/jpeg' %>
      </div>
      <div class="col-sm-4">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :solved, "Решена?", :class => 'control-label col-sm-5' %>
      <div class="col-sm-1">
        <%= f.check_box :solved %>
      </div>
      <div class="col-sm-6">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :answer, "Ответ", :class => 'control-label col-sm-5' %>
      <div class="col-sm-4">
        <%= f.text_area :answer, :class => 'form-control' %>
      </div>
      <div class="col-sm-3">
      </div>
    </div>


    <div class="form-group">
      <div class="col-sm-2">
      </div>
      <div class="col-sm-10" style="text-align: center">
        <%= f.submit "Сохранить изменения", {class: "btn btn-large btn-primary", style: "width: 170px"} %>
      </div>
    </div>

<% end %>

app/views/tasks/index.html.erb
<h1 id="h1_tasks">Все задачи</h1>


<%= link_to 'Создать задачу', new_task_path, class: 'btn btn-primary' %>

<hr/>

<div>
  <div id="univer_buttons">
    <a id="vutbr_show" class='btn btn-lg btn-primary univer_button' data-univer="1">Технический университет Брно</a>
    <a id="mas_show" class='btn btn-lg btn-primary univer_button' data-univer="2">Масариков университет</a>
  </div>
  <!--&lt;!&ndash;<div style="display: none" id="masarikov">&ndash;&gt;-->

  <div style="display: none" id="tasks_block">
    <!--</div>-->
    <a id="tasks_block_hide" class='btn btn-primary'>Назад</a>

    <hr/>
    <div id="index_filter" style="display: inline-block">
      <%= render 'index_filter' %>
    </div>

    <div id="tasks_list_content">
      <%= render 'tasks_list' %>
    </div>
    <br/>
  </div>

</div>
<br/>
<script>

    $(document).ready(function () {
        $(".univer_button").click(function (e) {
            console.log($(e.target).data().univer);
            $("#univer_search").val($(e.target).data().univer);
            $.rails.handleRemote($("#index_filter_form .current_page"));
            $("#univer_buttons").hide();
            $("#tasks_block").show();

        });
        $("#tasks_block_hide").click(function (e) {
            $("#univer_buttons").show();
            $("#tasks_block").hide();

        });

        if (window.location.hash == '#masarikov')  $("#mas_show").click();

        $(document).on('ajax:before', function (e) {
            console.log('ajax:before', e.target);
            $(e.target).data('params', $("#index_filter_form").serializeArray());
        });

        window.setup_handlers = function () {

            $("#index_filter_form select").change(function () {
                $.rails.handleRemote($("#index_filter_form .current_page"));
            });

        }
        window.setup_handlers();
    });
</script>

app/views/tasks/index.js.erb
console.log("index.js.erb works");
$('#tasks_content').html("<%= escape_javascript render('tasks_list_tr') %>");
$('#index_filter').html("<%= escape_javascript render('index_filter') %>");

$('#paginator').html('<%= escape_javascript(paginate(@tasks, :remote => true).to_s) %>');

window.setup_handlers();

app/views/tasks/new.html.erb
<%= form_for(@task, :url => {:controller => 'tasks', :action => 'create'},
             :html => {:class => 'form-horizontal', :role => 'form', multipart: true}) do |f| %>
    <%= render 'shared/error_messages' %>

    <div class="form-group">

      <%= link_to "Назад", root_path, :class => 'btn btn-primary col-sm-1' %>

      <div class="col-sm-11">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :univer, "Университет", :class => 'control-label col-sm-5' %>
      <div class="col-sm-3">
        <%= f.select :univer, [['Технический университет Брно', 1], ['Масариков университет', 2]], {}, {:class => "form-control"} %>
      </div>
      <div class="col-sm-4">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :variant, "Вариант №", :class => 'control-label col-sm-5' %>
      <div class="col-sm-3">
        <%= f.number_field :variant, :class => 'form-control' %>
      </div>
      <div class="col-sm-4">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :number, "Номер задачи", :class => 'control-label col-sm-5' %>
      <div class="col-sm-3">
        <%= f.number_field :number, :class => 'form-control' %>
      </div>
      <div class="col-sm-4">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :type_t, "Тип задачи", :class => 'control-label col-sm-5' %>
      <div class="col-sm-3">
        <%= f.text_field :type_t, :class => 'form-control' %>
      </div>
      <div class="col-sm-4">
      </div>
    </div>


    <div class="form-group">
      <%= f.label :czech_text, "Чешский текст", :class => 'control-label col-sm-5' %>
      <div class="col-sm-4">
        <%= f.text_area :czech_text, :class => 'form-control' %>
      </div>
      <div class="col-sm-4">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :russian_text, "Русский текст", :class => 'control-label col-sm-5' %>
      <div class="col-sm-4">
        <%= f.text_area :russian_text, :class => 'form-control' %>
      </div>
      <div class="col-sm-3">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :photo, "Добавить изображение", :class => 'control-label col-sm-5' %>
      <div class="col-sm-3">
        <%= f.file_field :photo, :class => 'filestyle', :accept => 'image/png,image/gif,image/jpeg' %>
      </div>
      <div class="col-sm-4">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :solved, "Решена?", :class => 'control-label col-sm-5' %>
      <div class="col-sm-1">
        <%= f.check_box :solved %>
      </div>
      <div class="col-sm-6">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :answer, "Ответ", :class => 'control-label col-sm-5' %>
      <div class="col-sm-4">
        <%= f.text_area :answer, :class => 'form-control' %>
      </div>
      <div class="col-sm-3">
      </div>
    </div>


    <hr>
    <div class="form-group">
      <div class="col-sm-2">
      </div>
      <div class="col-sm-10" style="text-align: center">
        <%= f.submit "Создать задачу", {class: "btn btn-large btn-primary", style: "width: 170px"} %>
      </div>
    </div>
<% end %>

app/views/tasks/show.html.erb
<%= form_for(@task, :url => {:controller => 'tasks', :action => 'show'},
             :html => {:class => 'form-horizontal', :role => 'form', multipart: true}) do |f| %>

    <h1>
      Задача <%= (@task.univer == 1 ? 'Технического университета Брно' : 'Масарикова университета') %>
      вариант <%= @task.variant %>, № <%= @task.number %>
    </h1>

    <div>
      <%= link_to 'Редактировать', edit_task_path(@task), :class => 'btn btn-primary' %>
      <%= link_to 'Удалить', @task, method: :delete,
                      data: {confirm: 'Вы уверены?'},  :class => 'btn btn-primary' %>
    </div>

    <hr/>

    <div class="form-group">
      <%= f.label :type_t, "Тип задачи", :class => 'control-label col-sm-2' %>
      <div class="col-sm-5">
        <%= @task.type_t %>
      </div>
      <div class="col-sm-5">
      </div>
    </div>

    <hr/>

    <div class="form-group">
      <%= f.label :czech_text, "Чешский", :class => 'control-label col-sm-2' %>
      <div class="col-sm-6">
        <%= markdown(@task.czech_text) %>
      </div>
      <div class="col-sm-4">
      </div>
    </div>

    <hr/>

    <div class="form-group">
      <%= f.label :russian_text, "Русский", :class => 'control-label col-sm-2' %>
      <div class="col-sm-6">
        <%= markdown(@task.russian_text) %>
      </div>
      <div class="col-sm-4">
      </div>
    </div>

    <hr/>

    <% if !(@task.photo.blank?) %>
        <div class="form-group">
          <div class="col-sm-1">
          </div>
          <div class="col-sm-11">
            <%= image_tag @task.photo.url %>
            <td><%= link_to 'Удалить картинку', delete_image_path(@task.id), method: :put %></td>
          </div>
        </div>
    <% end %>

    <hr/>

    <div class="form-group">
      <%= f.label :answer, "Ответ", :class => 'control-label col-sm-2' %>
      <div class="col-sm-6">
        <%= markdown(@task.answer) %>
      </div>
      <div class="col-sm-4">
      </div>
    </div>

<% end %>